### ISSUE TITLE
Discussion for Treasury Fund Rebalancing 

### ISSUE THREAD

**Issue by 0xxlegolas** [klaytn/kips#103]
This issue is created for discussions on how to rebalance the treasury funds after KGP-6.  

KGP-6 is the proposal for new token economy requires rebalancing of funds from KGF, KIR to KCF and KFF. For detailed information refer to [KGP-6](https://govforum.klaytn.foundation/t/kgp-6-proposal-to-establish-a-sustainable-and-verifiable-klay-token-economy/157).

This issue number will be used as a KIP number.

**Comment by aidan-kwon** [comment]
close via #104 #106
