### ISSUE TITLE
Discussion for Simple BLS Registry

### ISSUE THREAD

**Issue by ian0371** [klaytn/kips#113]
This issue is created for discussions on how to make interfaces for BLS registry.

BLS registry design is the first step to bring BLS crypto in Klaytn.
Further usages will be described in the following KIPs.

This issue number will be used as a KIP number.

**Comment by baerae-colin** [comment]
@ian0371 @aidan-kwon 
Do we also explore possibilities to implement new account key in Klaytn's account model?
For example, we can introduce a new key type for BLS.
