### ISSUE TITLE
Discussion for Supplant DIFFICULTY opcode with RANDOM

### ISSUE THREAD

**Issue by blukat29** [klaytn/kips#114]
This issue is created for discussions on "supplant DIFFICULTY opcode with RANDOM".

It will depend on BLS signatures and a RANDAO-like algorithm.
This random number will exist in block headers and could be used as a new proposer selection entropy.

This issue number will be used as a KIP number.

**Comment by ian0371** [comment]
I'll change the title to "Supplant DIFFICULTY opcode with RANDOM" because opRANDOM as well as new header fields are introduced.
